/*
// https://hermitcraft.fandom.com/wiki/Hermitcraft_Trading_Card_Game
copy(Array.from(temp1.children).map((row, index, arr) => {
  const columns = Array.from(row.children).map(col => col.querySelector('b') ? '#' + col.innerText : col.innerText)
  if (columns[0] === 'Rare') columns.unshift(arr[index - 1].children[0].innerText)
  if (columns[0] === 'Ultra Rare') columns.unshift(arr[index - 2].children[0].innerText)
  columns[0] = columns[0].trim()
  return columns
}))
*/
const scrappedList = [
	[
		'BdoubleO100',
		'Common',
		'Build',
		'260',
		'Gradient',
		'1 Build',
		'60',
		'Prettystone',
		'2 Build',
		'80',
		'',
	],
	[
		'BdoubleO100',
		'Rare',
		'Bal',
		'260',
		'Retexture',
		'1 Any',
		'60',
		'#Shreep',
		'2 Bal +\n\n1 Any',
		'00',
		"Bdubs sleeps for the next 2 turns. Can't attack. Restores Full health.\n\nCan still draw and attach cards while sleeping.\n\nCan't be used consecutively.",
	],
	[
		'Cubfan135',
		'Common',
		'Bal',
		'290',
		'Heyo',
		'1 Bal',
		'50',
		'Vex Magic',
		'1 Bal +\n\n1 Any',
		'70',
		'',
	],
	[
		'Cubfan135',
		'Rare',
		'Speed',
		'260',
		'Dash',
		'1 Any',
		'40',
		"#Let's Go",
		'3 Speed',
		'100',
		'After attack, Player can choose to swap Cubfan with AFK Hermit.',
	],
	[
		'Docm77',
		'Common',
		'Red',
		'260',
		'Hive Mind',
		'1 Any',
		'40',
		'G.O.A.T.',
		'1 Red +\n\n1 Any',
		'70',
		'',
	],
	[
		'Docm77',
		'Rare',
		'Farm',
		'280',
		'Shadow Tech',
		'1 Any',
		'40',
		'#World Eater',
		'2 Farm',
		'80',
		'Flip a Coin.\n\nIf heads, attack damage doubles.\n\nIf tails, attack damage is halved.',
	],
	[
		'EthosLab',
		'Common',
		'Bal',
		'260',
		'Snack Time',
		'1 Any',
		'40',
		'Breach',
		'3 Bal',
		'100',
		'',
	],
	[
		'EthosLab',
		'Rare',
		'Red',
		'280',
		'Oh Snappers',
		'1 Red',
		'50',
		'#Blue Fire',
		'2 Red',
		'80',
		'Flip a Coin.\n\nIf heads, this attack also BURNs the opponent. Does an additional +20HP damage per turn until opponent is knocked out.\n\nGoing AFK does not eliminate the BURN.',
	],
	[
		'EthosLab',
		'Ultra Rare',
		'PvP',
		'250',
		'Ladders',
		'1 Any',
		'30',
		'#Slab',
		'2 Any',
		'70',
		'Flip a Coin 3 times.\n\nDoes an additional +20HP damage for every heads.',
	],
	[
		'FalseSymmetry',
		'Common',
		'PVP',
		'250',
		'Queen of Hearts',
		'1 PvP',
		'50',
		'Eagle Eye',
		'1 PvP +\n\n1 Any',
		'70',
		'',
	],
	[
		'FalseSymmetry',
		'Rare',
		'Build',
		'250',
		'High Noon',
		'1 Build',
		'60',
		'#Supremacy',
		'1 Build +\n\n1 Any',
		'70',
		'Flip a Coin.\n\nIf heads, False also restores +40HP.',
	],
	[
		'GeminiTay',
		'Common',
		'Build',
		'300',
		'Cottagecore',
		'1 Build',
		'60',
		'Be Great',
		'3 Build',
		'100',
		'',
	],
	[
		'GeminiTay',
		'Rare',
		'Terra',
		'270',
		"It's Fine",
		'1 Terra',
		'60',
		'#Geminislay',
		'2 Terra',
		'80',
		'Flip a Coin.\n\nIf heads, Gem can play an additional effect card the same turn.',
	],
	[
		'Grian',
		'Common',
		'Build',
		'300',
		'Copper Golem',
		'1 Build',
		'60',
		'Waffle',
		'1 Build +\n\n1 Any',
		'70',
		'',
	],
	[
		'Grian',
		'Rare',
		'Prank',
		'300',
		'#Borrow',
		'2 Prank',
		'50',
		'Start a War',
		'3 Prank',
		'100',
		"Flip a Coin.\n\nIf heads, Grian takes opponent's active effect card.\n\nPlayer can choose to attach card or discard.",
	],
	[
		'GoodTimesWithScar',
		'Common',
		'Terra',
		'260',
		'Jellie Paws',
		'1 Terra',
		'50',
		'Hot Guy',
		'3 Terra',
		'100',
		'',
	],
	[
		'GoodTimesWithScar',
		'Rare',
		'Build',
		'270',
		'Scarred For Life',
		'1 Build',
		'50',
		'#Deathloop',
		'1 Build +\n\n1 Any',
		'70',
		'If Scar is knocked out the following turn, flip a coin.\n\nIf heads, Scar is revived with +50HP.\n\nCan only be revived once.',
	],
	[
		'Hypnotizd',
		'Common',
		'Bal',
		'250',
		'What Up',
		'1 Bal',
		'60',
		'Max Attack',
		'3 Bal',
		'100',
		'',
	],
	[
		'Hypnotizd',
		'Rare',
		'Mine',
		'270',
		'MmHmm',
		'1 Mine',
		'60',
		"#Got 'Em",
		'1 Mine +\n\n1 Any',
		'70',
		'Player can choose to have Hypno attack AFK opposing Hermits.',
	],
	[
		'iJevin',
		'Common',
		'Exp',
		'250',
		"Got 'Em",
		'1 Exp',
		'60',
		'Jevination',
		'2 Exp +\n\n1 Any',
		'90',
		'',
	],
	[
		'iJevin',
		'Rare',
		'Speed',
		'300',
		'Your Boi',
		'1 Any',
		'30',
		'#Peace Out',
		'2 Speed +\n\n1 Any',
		'90',
		'After attack, opponent is forced to replace active Hermit with AFK Hermit.\n\nIf there are no AFK Hermits, active Hermit remains in battle.',
	],
	[
		'ImpulseSV',
		'Common',
		'Farm',
		'270',
		'Shovel Shuffle',
		'1 Any',
		'30',
		'iAttack',
		'1 Farm +\n\n1 Any',
		'70',
		'',
	],
	[
		'ImpulseSV',
		'Rare',
		'Red',
		'250',
		'Bop',
		'1 Red',
		'50',
		'#Boomer',
		'1 Red +\n\n1 Any',
		'70',
		'Does an additional +40HP damage for every AFK Boomer (Bdubs, Tango) up to a maximum of +80HP damage.',
	],
	[
		'Iskall85',
		'Common',
		'Bal',
		'280',
		'Hallo',
		'1 Bal',
		'50',
		'Omega',
		'3 Bal',
		'100',
		'',
	],
	[
		'Iskall85',
		'Rare',
		'Farm',
		'290',
		'Of Doom',
		'1 Farm',
		'50',
		'#Bird Poop',
		'2 Farm',
		'80',
		'Does double damage versus Builder types.',
	],
	[
		'JoeHills',
		'Common',
		'Exp',
		'270',
		'Howdy',
		'1 Any',
		'30',
		'Haiku',
		'2 Exp +\n\n1 Any',
		'90',
		'',
	],
	[
		'JoeHills',
		'Rare',
		'Farm',
		'270',
		'Grow Hills',
		'1 Exp',
		'50',
		'#Time Skip',
		'2 Farm +\n\n1 Any',
		'90',
		'Flip a Coin.\n\nIf heads, opponent skips next turn.\n\nCannot be used consecutively.',
	],
	[
		'Keralis',
		'Common',
		'Build',
		'270',
		'Looky Looky',
		'1 Any',
		'40',
		'NoNoNoNo',
		'2 Build +\n\n1 Any',
		'90',
		'',
	],
	[
		'Keralis',
		'Rare',
		'Terra',
		'250',
		'Booshes',
		'1 Any',
		'60',
		'#Sweet Face',
		'2 Terra +\n\n1 Any',
		'00',
		'Heals any AFK Hermit +100HP.\n\nCannot be used consecutively.',
	],
	[
		'MumboJumbo',
		'Common',
		'Red',
		'270',
		'Chuffed to Bits',
		'1 Red',
		'50',
		'Spoon',
		'2 Red',
		'80',
		'',
	],
	[
		'MumboJumbo',
		'Rare',
		'Prank',
		'290',
		'Moustache',
		'1 Prank',
		'60',
		'#Quite Simple',
		'2 Prank',
		'40',
		'Flip a Coin twice.\n\n+40 HP damage for every heads.\n\nTotal damage doubles if at least 1 other Prankster type is AFK.\n\nIf player does not roll heads at least once, the above does not apply.',
	],
	[
		'PearlescentMoon',
		'Common',
		'Build',
		'270',
		'5 AM',
		'1 Any',
		'40',
		"What's This?",
		'2 Build +\n\n1 Any',
		'90',
		'',
	],
	[
		'PearlescentMoon',
		'Rare',
		'Terra',
		'300',
		'Cleaning Lady',
		'1 Terra',
		'60',
		'#Aussie Ping',
		'1 Terra +\n\n1 Any',
		'70',
		'Opponent flips a coin on their next turn.\n\nIf heads, their attack misses.',
	],
	[
		'Rendog',
		'Common',
		'Bal',
		'260',
		'Professional',
		'1 Bal',
		'50',
		'Outrageous',
		'3 Bal',
		'100',
		'',
	],
	[
		'Rendog',
		'Rare',
		'Build',
		'290',
		"Comin' At Ya",
		'1 Build',
		'50',
		'#Role Play',
		'3 Build',
		'00',
		'Ren mimics special move of the opposing Hermit.',
	],
	[
		'StressMonster101',
		'Common',
		'Build',
		'280',
		"'Ello",
		'1 Build',
		'50',
		'Geezer',
		'2 Build',
		'80',
		'',
	],
	[
		'StressMonster101',
		'Rare',
		'Prank',
		'300',
		'Plonker',
		'1 Prank',
		'50',
		'#Yolo',
		'3 Prank',
		'00',
		'This attack instantly knocks out opposing Hermit as well as the player.',
	],
	[
		'TangoTek',
		'Common',
		'Red',
		'300',
		'Thing-ificator',
		'1 Red',
		'60',
		'Hat Trick',
		'1 Red +\n\n1 Any',
		'70',
		'',
	],
	[
		'TangoTek',
		'Rare',
		'Farm',
		'290',
		'Skadoodle',
		'1 Farm',
		'50',
		'#Extra Flee',
		'3 Farm',
		'100',
		'At the end of the turn, both Tango and opposing Hermit are replaced by AFK Hermits.\n\nOpponent must select replacement first.\n\nIf there are no AFK Hermits, active Hermit remains in battle.',
	],
	[
		'TinFoilChef',
		'Common',
		'Mine',
		'290',
		'=π',
		'1 Any',
		'40',
		'Alright',
		'2 Mine +\n\n1 Any',
		'90',
		'',
	],
	[
		'TinFoilChef',
		'Rare',
		'Mine',
		'300',
		'True Hermit',
		'1 Any',
		'40',
		'#Branch Mine',
		'2 Mine',
		'80',
		'Flip a Coin.\n\nIf heads, player draws another card at the end of their turn.',
	],
	[
		'TinFoilChef',
		'Ultra Rare',
		'Mine',
		'300',
		'Phone Call',
		'1 Mine',
		'60',
		'#Take It Easy',
		'3 Mine',
		'100',
		'Flip a Coin.\n\nIf heads, opponent is forced to discard effect card attached to active Hermit.\n\nOnly one effect card per opposing Hermit can be discarded.',
	],
	[
		'VintageBeef',
		'Common',
		'Bal',
		'250',
		'Hey Guys!',
		'1 Any',
		'30',
		'Mindcrack',
		'2 Bal',
		'80',
		'',
	],
	[
		'VintageBeef',
		'Rare',
		'Build',
		'290',
		'Poik',
		'1 Any',
		'40',
		'#Beefy Tunes',
		'2 Build',
		'80',
		"Flip a Coin.\n\nIf heads, this attack also removes all status effects from user's active and AFK Hermits.",
	],
	[
		'VintageBeef',
		'Ultra Rare',
		'Exp',
		'280',
		'Back in Action',
		'1 Any',
		'40',
		'#N.H.O',
		'3 Exp',
		'100',
		'If user has Doc, Bdubs, and Etho as AFK, attack damage doubles.',
	],
	[
		'Welsknight',
		'Common',
		'Build',
		'300',
		'Chivalry',
		'1 Any',
		'40',
		'Judgement',
		'2 Build +\n\n1 Any',
		'90',
		'',
	],
	[
		'Welsknight',
		'Rare',
		'PvP',
		'280',
		"Knight's Blade",
		'1 Any',
		'40',
		'#Vengeance',
		'3 PvP',
		'100',
		"If Welsknight's HP is orange, Vengeance does +20HP damage.\n\nIf Welsknight's HP is red, Vengeance does +50HP damage.",
	],
	[
		'XBCrafted',
		'Common',
		'PvP',
		'270',
		'Aww Yeah',
		'1 PvP',
		'50',
		'Blam!',
		'2 PvP',
		'80',
		'',
	],
	[
		'XBCrafted',
		'Rare',
		'Exp',
		'270',
		'Giggle',
		'1 Exp',
		'50',
		'#Noice!',
		'1 Exp +\n\n1 Any',
		'70',
		'Noice! ignores any effect cards attached to opposing Hermit.',
	],
	[
		'Xisumavoid',
		'Common',
		'Farm',
		'300',
		'Oh My Days',
		'1 Farm',
		'60',
		'Jeez',
		'2 Farm +\n\n1 Any',
		'90',
		'',
	],
	[
		'Xisumavoid',
		'Rare',
		'Red',
		'280',
		'Goodness Me',
		'1 Red',
		'60',
		'#Cup of Tea',
		'2 Red',
		'80',
		'Flip a Coin.\n\nIf heads, this attack also POISONS the opponent. Does an additional +20HP damage per turn until opponent is knocked out.\n\nGoing AFK does not eliminate the POISON.',
	],
	[
		'ZedaphPlays',
		'Common',
		'Red',
		'250',
		'For Science',
		'1 Red',
		'50',
		'Hadjah!',
		'1 Red +\n\n1 Any',
		'70',
		'',
	],
	[
		'ZedaphPlays',
		'Rare',
		'Exp',
		'290',
		'#Sheep Stare',
		'1 EXP',
		'50',
		'Get Dangled',
		'2 Exp',
		'80',
		'Flip a Coin.\n\nIf heads, opponent flips a coin their next turn.\n\nIf heads, opponent damages themselves.',
	],
	[
		'ZombieCleo',
		'Common',
		'Build',
		'260',
		"It's Fine",
		'1 Build',
		'60',
		'Revenge',
		'2 Build',
		'80',
		'',
	],
	[
		'ZombieCleo',
		'Rare',
		'PvP',
		'290',
		'Dismissed',
		'1 PvP',
		'60',
		'#Puppetry',
		'3 PvP',
		'00',
		'Player uses a move from any of their AFK Hermits.',
	],
]

const HERMIT_TYPES = {
	bal: 'balanced',
	build: 'builder',
	speed: 'speedrunner',
	red: 'redstone',
	farm: 'farm',
	pvp: 'pvp',
	terra: 'terraform',
	prank: 'prankster',
	mine: 'miner',
	exp: 'explorer',
	any: 'any',
}

const HERMIT_SHORT_NAMES = {
	BdoubleO100: 'Bdubs',
	Cubfan135: 'Cub',
	Docm77: 'Docm77',
	EthosLab: 'Etho',
	FalseSymmetry: 'False',
	GeminiTay: 'Gem',
	Grian: 'Grain',
	GoodTimesWithScar: 'Scar',
	Hypnotizd: 'Hypno',
	iJevin: 'Jevin',
	ImpulseSV: 'Impulse',
	Iskall85: 'Iskall',
	JoeHills: 'Joe',
	Keralis: 'Keralis',
	MumboJumbo: 'Mumbo',
	PearlescentMoon: 'Pearl',
	Rendog: 'Rendog',
	StressMonster101: 'Stress',
	TangoTek: 'Tango',
	TinFoilChef: 'TFC',
	VintageBeef: 'Beef',
	Welsknight: 'Wels',
	XBCrafted: 'XB',
	Xisumavoid: 'Xisuma',
	ZedaphPlays: 'Zedaph',
	ZombieCleo: 'Cleo',
}

const getCost = (str) => {
	return str
		.replaceAll('\n', '')
		.split('+')
		.reduce((result, part) => {
			part = part.trim()
			const [total, typeStr] = part.split(' ')
			if (!HERMIT_TYPES.hasOwnProperty(typeStr.toLowerCase()))
				throw new Error('Unknown type: ' + typeStr)
			const type = HERMIT_TYPES[typeStr.toLowerCase()]
			for (let i = 0; i < total; i++) result.push(type)
			return result
		}, [])
}

const makeHermitCard = (source) => ({
	id: `${source[0].toLowerCase()}_${source[1]
		.toLowerCase()
		.replaceAll(' ', '_')}`,
	rarity: source[1].toLowerCase().replaceAll(' ', '_'),
	hermitType: HERMIT_TYPES[source[2].toLowerCase()],
	name: HERMIT_SHORT_NAMES[source[0]],
	health: Number(source[3]),
	primary: {
		name: source[4].replace('#', ''),
		cost: getCost(source[5]),
		damage: Number(source[6]),
		power: source[4].startsWith('#')
			? {
					type: source[4].replace('#', '').toLowerCase(),
					description: source[10],
			  }
			: null,
	},
	secondary: {
		name: source[7].replace('#', ''),
		cost: getCost(source[8]),
		damage: Number(source[9]),
		power: source[7].startsWith('#')
			? {
					type: source[7].replace('#', '').toLowerCase(),
					description: source[10],
			  }
			: null,
	},
	type: 'hermit',
})

export default scrappedList.reduce((result, item) => {
	const card = makeHermitCard(item)
	result[card.id] = card
	return result
}, {})
