export default {
	server: {
		port: 9000,
		clientDevPort: 3002,
		clientPath: 'client/dist',
		cors: [
			'http://localhost:3002',
			'https://hc-tcg-beta.fly.dev',
			'https://hc-tcg-testing.fly.dev',
			'https://hc-tcg.online',
			'https://testing.hc-tcg.online',
		],
		world: 'LTF42',
		logoSubText: '10k games since 1.0!',
	},
	game: {
		limits: {
			maxTurnTime: 90,
			extraActionTime: 30,
			minCards: 42,
			maxCards: 42,
			maxDuplicates: 3,
			maxDeckCost: 42,
			bannedCards: ['evilxisuma_boss', 'feather', 'item_any_rare'],
			disabledCards: ['iskallman_common', 'iskallman_rare'],
			rematchTime: 90 * 1000,
			gameTimeout: 1000 * 60 * 60 * 2 /* 2 hours */,
		},
		replayVersion: 0x02,
		disableDeckValidation: false,
		extraStartingCards: [],
		noItemRequirements: false,
		forceCoinFlip: false,
		oneShotMode: false,
		disableDamage: false,
		disableDeckOut: false,
		startWithAllCards: false,
		unlimitedCards: false,
		blockedActions: [],
		availableActions: [],
		shuffleDeck: true,
		logErrorsToStderr: true,
		verboseLogging: true,
		showHooksState: {
			enabled: false,
			clearConsole: true,
		},
		autoEndTurn: false,
		logAttackHistory: false,
		disableRewardCards: false,
		renderCardsDynamically: false,
	},
	unlockAllCosmetics: false,
	statsUrl: null,
}
