version: '2.1'
services:
  hctcg:
    image: benji42/hc-tcg:latest
    container_name: hc-tcg
    ports:
      - 9000:9000
    volumes:
      - hc-tcg:/app
    restart: unless-stopped
volumes:
  hc-tcg:
