# fly.toml app configuration file generated for hc-tcg on 2024-11-14T00:34:36-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hc-tcg'
primary_region = 'bos'
kill_signal = 'SIGINT'
kill_timeout = '15s'

[experimental]
  cmd = ['npm', 'run', 'start']
  auto_rollback = true

[build]
  image = 'benji42/hc-tcg:latest'

[[services]]
  protocol = 'tcp'
  internal_port = 9000
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 500
    soft_limit = 450

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '4s'

[[vm]]
  size = 'shared-cpu-4x'
