export default {
	disableDeckValidation: false,
	extraStartingCards: [],
	noItemRequirements: false,
	forceCoinFlip: false,
	oneShotMode: false,
	disableDamage: false,
	disableDeckOut: false,
	startWithAllCards: false,
	unlimitedCards: false,
	blockedActions: [],
	availableActions: [],
	shuffleDeck: true,
	logErrorsToStderr: true,
	verboseLogging: true,
	showHooksState: {
		enabled: false,
		clearConsole: true,
	},
	autoEndTurn: false,
	logAttackHistory: false,
	disableRewardCards: false,
	renderCardsDynamically: false,
	statsUrl: null,
}
