export const universe = [
	'bdoubleo100_common',
	'bdoubleo100_rare',
	'bed',
	'bow',
	'chest',
	'chorus_fruit',
	'clock',
	'composter', //
	'crossbow',
	'cubfan135_common',
	'cubfan135_rare', //10
	'curse_of_binding',
	'curse_of_vanishing',
	'diamond_armor',
	'diamond_sword', //14
	'docm77_common',
	'docm77_rare',
	'efficiency',
	'emerald',
	'ethoslab_common',
	'ethoslab_rare', //20
	'ethoslab_ultra_rare',
	'falsesymmetry_common',
	'falsesymmetry_rare',
	'fishing_rod', //24
	'flint_&_steel',
	'fortune',
	'geminitay_common',
	'geminitay_rare',
	'gold_armor',
	'golden_apple',
	'golden_axe',
	'goodtimeswithscar_common',
	'goodtimeswithscar_rare',
	'grian_common',
	'grian_rare',
	'hypnotizd_common',
	'hypnotizd_rare',
	'ijevin_common',
	'ijevin_rare',
	'impulsesv_common',
	'impulsesv_rare',
	'instant_health', //42
	'instant_health_ii',
	'invisibility_potion',
	'iron_armor',
	'iron_sword',
	'iskall85_common',
	'iskall85_rare',
	'item_balanced_common', //49
	'item_balanced_rare',
	'item_builder_common',
	'item_builder_rare',
	'item_explorer_common',
	'item_explorer_rare',
	'item_farm_common',
	'item_farm_rare',
	'item_miner_common',
	'item_miner_rare',
	'item_prankster_common',
	'item_prankster_rare',
	'item_pvp_common',
	'item_pvp_rare',
	'item_redstone_common',
	'item_redstone_rare',
	'item_speedrunner_common',
	'item_speedrunner_rare',
	'item_terraform_common',
	'item_terraform_rare',
	'joehills_common', // 69
	'joehills_rare',
	'keralis_common',
	'keralis_rare',
	'knockback',
	'lava_bucket',
	'lead',
	'looting',
	'loyalty',
	'mending',
	'milk_bucket',
	'mumbojumbo_common', //80
	'mumbojumbo_rare',
	'netherite_armor',
	'netherite_sword',
	'pearlescentmoon_common',
	'pearlescentmoon_rare',
	'rendog_common',
	'rendog_rare',
	'shield', //88
	'splash_potion_of_healing',
	'splash_potion_of_poison',
	'spyglass',
	'stressmonster101_common',
	'stressmonster101_rare',
	'tangotek_common',
	'tangotek_rare',
	'thorns',
	'tinfoilchef_common', //97
	'tinfoilchef_rare',
	'tinfoilchef_ultra_rare',
	'tnt',
	'totem',
	'vintagebeef_common',
	'vintagebeef_rare',
	'vintagebeef_ultra_rare',
	'water_bucket',
	'welsknight_common',
	'welsknight_rare',
	'wolf', //108
	'xbcrafted_common',
	'xbcrafted_rare',
	'xisumavoid_common',
	'xisumavoid_rare',
	'zedaphplays_common',
	'zedaphplays_rare',
	'zombiecleo_common',
	'zombiecleo_rare',

	// why does this exist
	'dream', //117

	// new cards, in final order
	'armor_stand',
	'chainmail_armor',
	'command_block',
	'lightning_rod',
	'string',
	'thorns_ii',
	'thorns_iii',
	'turtle_shell',

	'beetlejhost_common',
	'eviljevin_common',
	'evilxisuma_rare',
	'goatfather_rare',
	'helsknight_rare',
	'hotguy_rare',
	'humancleo_rare', //32
	'jingler_rare',
	'llamadad_rare',
	'potatoboy_rare',
	'poultryman_common',
	'renbob_rare',

	'anvil', //38
	'bad_omen',
	'egg',
	'ender_pearl',
	'fire_charge',
	'ladder',
	'piston',
	'potion_of_slowness',
	'potion_of_weakness',
	'splash_potion_of_healing_ii',
	'sweeping_edge',
	'target_block',
	'trident', //150
]
