name: Fuzz Tests

on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  issues: write

jobs:
  fuzz:
    name: Fuzz Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      failed_test: ${{ steps.fuzz.outputs.test }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 2

      - name: Setup Node
        run: |
          npm install

      - name: Create debug config
        run: cp ./common/config/debug-config.example.js ./common/config/debug-config.js

      - name: Run Fuzz Tests
        id: fuzz
        run: |
            echo "Starting fuzz tests...";
            FUZZ_RESULT=$(npm run test:fuzz -- fuzz 20 --fail-fast 2>&1 | tail -n 1);
            echo $FUZZ_RESULT;
            if echo $FUZZ_RESULT | grep 'FAIL'; then
              SEED=$(echo $FUZZ_RESULT | cut -d ":" -f1);
              echo "$SEED"
              echo "test=$SEED" >> "$GITHUB_OUTPUT";
            else
               echo "No tests failed... doing nothing";
               echo "test=NOTHING" >> "$GITHUB_OUTPUT";
            fi;

  make_issue:
    name: Make Issue If Neccesary
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: fuzz
    if: "${{ needs.fuzz.outputs.failed_test != 'NOTHING' }}"
    steps:
      - run: echo "$SEED"
      - name: Create issue
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Fuzz Testing Failure Detected (`${{ needs.fuzz.outputs.failed_test }}`)
          LABELS: fuzz testing
          BODY: |
            Fuzz Testing Failure Detected. Check with the folliwng command:
            ```sh
            npm run test:fuzz -- debug ${{ needs.fuzz.outputs.failed_test }}
            ```
          PINNED: false
          CLOSE_PREVIOUS: false

