name: Fuzz Tests

on:
  workflow_dispatch:
  push:

jobs:
  fuzz:
    name: Fuzz Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      failed_test: ${{ steps.step1.outputs.test }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 2

      - name: Setup Node
        run: |
          npm install

      - name: Create debug config
        run: cp ./common/config/debug-config.example.js ./common/config/debug-config.js

      - name: Run Fuzz Tests
        run: |
            echo "Starting fuzz tests...";
            FUZZ_RESULT=$(npm run test:fuzz -- fuzz 5 --fail-fast 2>&1 | tail -n 1);
            echo $FUZZ_RESULT;
            if echo $FUZZ_RESULT | grep 'FAIL'; then
              SEED=$(echo $FUZZ_RESULT | cut -d ":" -f1);
              echo "test=$SEED" >> "$GITHUB_OUTPUT";
            else
               echo "No tests failed... doing nothing";
               echo "test=NOTHING" >> "$GITHUB_OUTPUT";
            fi;

  make_issue:
    name: Make Issue If Neccesary
    runs-on: ubuntu-latest
    needs: fuzz
    if: "${{ needs.fuzz.outputs.failed_test != 'NOTHING' }}"
    steps:
      - run: echo "$SEED"

      - name: Check out repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 2

      - uses: JasonEtco/create-an-issue@v2
        env:
          SEED: ${{ needs.fuzz.outputs.failed_test }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/fuzz-testing-failure.md

